# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/mithi/RISV/RISV.srcs/sources_1/ip/fpd_cmp/fpd_cmp.xci
# IP: The module: 'fpd_cmp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mithi/RISV/RISV.gen/sources_1/ip/fpd_cmp/fpd_cmp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpd_cmp'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/mithi/RISV/RISV.srcs/sources_1/ip/fpd_cmp/fpd_cmp.xci
# IP: The module: 'fpd_cmp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mithi/RISV/RISV.gen/sources_1/ip/fpd_cmp/fpd_cmp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpd_cmp'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
