# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mithi/RISV/RISV.srcs/sources_1/ip/FIFO_FWFT/FIFO_FWFT.xci
# IP: The module: 'FIFO_FWFT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mithi/RISV/RISV.gen/sources_1/ip/FIFO_FWFT/FIFO_FWFT.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_FWFT'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/mithi/RISV/RISV.gen/sources_1/ip/FIFO_FWFT/FIFO_FWFT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_FWFT'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/mithi/RISV/RISV.srcs/sources_1/ip/FIFO_FWFT/FIFO_FWFT.xci
# IP: The module: 'FIFO_FWFT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mithi/RISV/RISV.gen/sources_1/ip/FIFO_FWFT/FIFO_FWFT.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_FWFT'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/mithi/RISV/RISV.gen/sources_1/ip/FIFO_FWFT/FIFO_FWFT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_FWFT'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
